### ISSUE TITLE
Chrome webstore only offers Version 11, yet 42 is required.

### ISSUE THREAD

**Issue by aknight2015** [nE0sIghT/gnome-browser-extension-mirror#117]
I can't install any extensions via chrome or firefox because the version offered through the Gnome extensions site and the chrome webstore is version 11. Yet the Gnome extensions site requires version 42.

**Comment by nE0sIghT** [comment]
The message at website is about [GNOME browser connector](https://repology.org/project/gnome-browser-connector/versions) which is at version 42.1.  
GNOME browser extension latest version is 11.  

See also https://wiki.gnome.org/Projects/GnomeShellIntegration/Installation
