### ISSUE TITLE
Error message when accessing GNOME extensions 

### ISSUE THREAD

**Issue by cosmi310599** [nE0sIghT/gnome-browser-extension-mirror#119]
Hi, when attempting to access to https://extensions.gnome.org/ I get the message error: **Native host has exited**

I have tried to access by launching this command : `google-chrome-stable https://extensions.gnome.org/` to see the logs and it returns this:

```
❯[12046:12046:0100/000000.910717:ERROR:gl_angle_util_vulkan.cc(189)] Failed to retrieve vkGetInstanceProcAddr
[12046:12046:0100/000000.910797:ERROR:vulkan_instance.cc(91)] Failed to get vkGetInstanceProcAddr pointer from ANGLE.
```

How can I fix this? thanks for your time!!

**Comment by nE0sIghT** [comment]
Do you using Arch?

**Comment by cosmi310599** [comment]
Yes

**Comment by nE0sIghT** [comment]
This is Arch issue. You can get help here: https://aur.archlinux.org/packages/gnome-browser-connector#comment-914291

**Comment by cosmi310599** [comment]
I will take a look, thanks 😊
